// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Business.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SevenTiny.GRpc.Protocol {

  /// <summary>Holder for reflection information generated from Business.proto</summary>
  public static partial class BusinessReflection {

    #region Descriptor
    /// <summary>File descriptor for Business.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BusinessReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5CdXNpbmVzcy5wcm90bxIXU2V2ZW5UaW55LkdScGMuUHJvdG9jb2waC01v",
            "ZGVsLnByb3RvMuABCg9CdXNpbmVzc1NlcnZpY2USYgoEVGVzdBIqLlNldmVu",
            "VGlueS5HUnBjLlByb3RvY29sLk1vZGVsLlJlcXVlc3RBcmdzGiwuU2V2ZW5U",
            "aW55LkdScGMuUHJvdG9jb2wuTW9kZWwuT3BlcmF0ZVJlc3VsdCIAEmkKC0dl",
            "dFNob3BOYW1lEiouU2V2ZW5UaW55LkdScGMuUHJvdG9jb2wuTW9kZWwuUmVx",
            "dWVzdEFyZ3MaLC5TZXZlblRpbnkuR1JwYy5Qcm90b2NvbC5Nb2RlbC5PcGVy",
            "YXRlUmVzdWx0IgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SevenTiny.GRpc.Protocol.Model.ModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
