/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace SevenTiny.Thrift.Contract
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TestArgs : TBase
  {
    private string _Remark;

    public long TrxnId { get; set; }

    public string TrxnName { get; set; }

    public int TrxnAmount { get; set; }

    public string TrxnType { get; set; }

    public string Remark
    {
      get
      {
        return _Remark;
      }
      set
      {
        __isset.Remark = true;
        this._Remark = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Remark;
    }

    public TestArgs() {
    }

    public TestArgs(long TrxnId, string TrxnName, int TrxnAmount, string TrxnType) : this() {
      this.TrxnId = TrxnId;
      this.TrxnName = TrxnName;
      this.TrxnAmount = TrxnAmount;
      this.TrxnType = TrxnType;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_TrxnId = false;
        bool isset_TrxnName = false;
        bool isset_TrxnAmount = false;
        bool isset_TrxnType = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I64) {
                TrxnId = iprot.ReadI64();
                isset_TrxnId = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                TrxnName = iprot.ReadString();
                isset_TrxnName = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                TrxnAmount = iprot.ReadI32();
                isset_TrxnAmount = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                TrxnType = iprot.ReadString();
                isset_TrxnType = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.String) {
                Remark = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_TrxnId)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field TrxnId not set");
        if (!isset_TrxnName)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field TrxnName not set");
        if (!isset_TrxnAmount)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field TrxnAmount not set");
        if (!isset_TrxnType)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field TrxnType not set");
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TestArgs");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        field.Name = "TrxnId";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(TrxnId);
        oprot.WriteFieldEnd();
        if (TrxnName == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field TrxnName not set");
        field.Name = "TrxnName";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(TrxnName);
        oprot.WriteFieldEnd();
        field.Name = "TrxnAmount";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TrxnAmount);
        oprot.WriteFieldEnd();
        if (TrxnType == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field TrxnType not set");
        field.Name = "TrxnType";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(TrxnType);
        oprot.WriteFieldEnd();
        if (Remark != null && __isset.Remark) {
          field.Name = "Remark";
          field.Type = TType.String;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Remark);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TestArgs(");
      __sb.Append(", TrxnId: ");
      __sb.Append(TrxnId);
      __sb.Append(", TrxnName: ");
      __sb.Append(TrxnName);
      __sb.Append(", TrxnAmount: ");
      __sb.Append(TrxnAmount);
      __sb.Append(", TrxnType: ");
      __sb.Append(TrxnType);
      if (Remark != null && __isset.Remark) {
        __sb.Append(", Remark: ");
        __sb.Append(Remark);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
