/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace SevenTiny.Thrift.Contract
{
  public enum TestResult
  {
    SUCCESS = 0,
    FAILED = 1,
  }
}
